<?php
$BASE_URL = "http://" . $_SERVER['SERVER_NAME'] . dirname($_SERVER['REQUEST_URI'] . '?') . '/';


// CONCATENAR COM SERVER NAME DA O LOCAL HOST 
// DIRNAME FUNÇÃO DO PHP QUE VAI CHAMAR O SERVER 'REQUEST_URI'

// ISSO VAI fICAR NA BASE URL

// E BASICAMENTE VAI DIZER AONDE É A RAIZ DO NOSSO SISTEMA PARA
// PARA QUE A GENTE POSSA LINKAR IMAGENS E ESTILOS
